if(SSQT_DBI_BOTAN2)
    message(STATUS "> Botan2 download/build/install ........ Enable")
else()
    message(STATUS "> Botan2 Search from Host System ....... Enable")
endif()

if(SSQT_BUILD_TEST)
    message(STATUS "> ShadowSocks Test Case Build .......... Enable")
else()
    message(STATUS "> ShadowSocks Test Case Build .......... Disable")
endif()

if(SSQT_BUILD_SHARED)
    message(STATUS "> ShadowSocks C/S Shared Build ......... Enable")
else()
    message(STATUS "> ShadowSocks C/S Static Build ......... Enable")
endif()

if(SSQT_BUILD_TUI)
    message(STATUS "> ShadowSocks Server/Client TUI Build .. Enable")
else()
    message(STATUS "> ShadowSocks Server/Client TUI Build .. Disable")
endif()

if(SSQT_BUILD_GUI)
    message(STATUS "> ShadowSocks Server/Client GUI Build .. Enable")
else()
    message(STATUS "> ShadowSocks Server/Client GUI Build .. Disable")
endif()
