if(SSQTL_DBI_BOTAN2)
    message(STATUS "> Botan2 download/build/install ........ Enable")
else()
    message(STATUS "> Botan2 Search from Host System ....... Enable")
endif()

if(SSQTL_BUILD_TEST)
    message(STATUS "> ShadowSocks Core Library Qt5 Test .... Enable")
else()
    message(STATUS "> ShadowSocks Core Library Qt5 Test .... Disable")
endif()

if(SSQTL_BUILD_SSTUI)
    message(STATUS "> ShadowSocks Server/Client TUI Build .. Enable")
else()
    message(STATUS "> ShadowSocks Server/Client TUI Build .. Disable")
endif()

if(SSQTL_BUILD_SHARED)
    message(STATUS "> ShadowSocks Core Shared Build ........ Enable")
else()
    message(STATUS "> ShadowSocks Core Shared Build ........ Disable")
endif()
